//
// The contents of this file are subject to the Mozilla Public
// License Version 1.1 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy
// of the License at http://www.mozilla.org/MPL/
// 
// Software distributed under the License is distributed on an
// "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
// implied. See the License for the specific language governing
// rights and limitations under the License.
// 
// The Original Code is State Machine Compiler (SMC).
// 
// The Initial Developer of the Original Code is Charles W. Rapp.
// Portions created by Charles W. Rapp are
// Copyright (C) 2005 - 2009. Charles W. Rapp.
// All Rights Reserved.
//
// Port to JavaScript by Francois Perrad
// All Rights Reserved.
//
// Contributor(s):
//
// RCS ID
// $Id$
//
// CHANGE LOG
// (See the bottom of this file.)
//

package net.sf.smc.generator;

import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import net.sf.smc.model.SmcAction;
import net.sf.smc.model.SmcElement;
import net.sf.smc.model.SmcElement.TransType;
import net.sf.smc.model.SmcFSM;
import net.sf.smc.model.SmcGuard;
import net.sf.smc.model.SmcMap;
import net.sf.smc.model.SmcParameter;
import net.sf.smc.model.SmcState;
import net.sf.smc.model.SmcTransition;
import net.sf.smc.model.SmcVisitor;

/**
 * Visits the abstract syntax tree, emitting Java code.
 * @see SmcElement
 * @see SmcCodeGenerator
 * @see SmcVisitor
 * @see SmcOptions
 *
 * @author Francois Perrad
 */

public final class SmcJSGenerator
    extends SmcCodeGenerator
{
//---------------------------------------------------------------
// Member methods
//

    //-----------------------------------------------------------
    // Constructors.
    //

    /**
     * Creates a Java code generator for the given options.
     * @param options The target code generator options.
     */
    public SmcJSGenerator(final SmcOptions options)
    {
        super (options, "js");
    } // end of SmcJSGenerator(SmcOptions)

    //
    // end of Constructors.
    //-----------------------------------------------------------

    //-----------------------------------------------------------
    // SmcVisitor Abstract Method Impelementation.
    //

    /**
     * Emits JavaScript code for the finite state machine context
     * class.
     * @param fsm emit JavaScript code for this finite state machine.
     */
    public void visit(SmcFSM fsm)
    {
        String rawSource = fsm.getSource();
        String context = fsm.getContext();
        String fsmClassName = fsm.getFsmClassName();
        String startState = fsm.getStartState();
        List<SmcMap> maps = fsm.getMaps();
        List<SmcTransition> transitions = fsm.getTransitions();
        Iterator<SmcParameter> pit;
        String transName;
        String javaState;
        String separator;
        int index;
        List<SmcParameter> params;

        _source.println("/*");
        _source.println(" * ex: set ro:");
        _source.println(" * DO NOT EDIT.");
        _source.println(" * generated by smc (http://smc.sourceforge.net/)");
        _source.print(" * from file : ");
        _source.print(_srcfileBase);
        _source.println(".sm");
        _source.println(" */");
        _source.println();

        // Dump out the raw source code, if any.
        if (rawSource != null && rawSource.length() > 0)
        {
            _source.println(rawSource);
            _source.println();
        }

        // Do user-specified imports now.
        for (String imp: fsm.getImports())
        {
            _source.print("require('");
            _source.print(imp);
            _source.println("');");
        }

        // Declare the abstract state class.
        _source.println();
        _source.print("function ");
        _source.print(context);
        _source.println("State () {}");
        // Inheritance.
        _source.print(context);
        _source.println("State.prototype = new State();");
        _source.println();

        _source.println("var _empty = function () {};");
        _source.print(context);
        _source.println("State.prototype.Entry = _empty;");
        _source.print(context);
        _source.println("State.prototype.Exit = _empty;");
        _source.println();

        _source.println("var _default = function (fsm) {");
        _source.println("    this.Default(fsm);");
        _source.println("};");

        // Generate the default transition definitions.
        for (SmcTransition trans: transitions)
        {
            transName = trans.getName();

            // Don't generate the Default transition here.
            if (transName.equals("Default") == false)
            {
                _source.print(context);
                _source.print("State.prototype.");
                _source.print(transName);
                _source.println(" = _default;");
            }
        }

        // Generate the overall Default transition for all maps.
        _source.println();
        _source.print(context);
        _source.println("State.prototype.Default = function (fsm) {");

        if (_debugLevel >= DEBUG_LEVEL_0)
        {
            _source.println("    if (fsm.debugFlag) {");
            _source.println("        fsm.debugStream.write(\"TRANSITION      : Default\\n\");");
            _source.println("    }");
        }

        _source.println("    var msg = \"Undefined Transition\\nState: \"");
        _source.println("            + fsm.getState().name");
        _source.println("            + \"\\nTransition: \"");
        _source.println("            + fsm.transition");
        _source.println("            + \"\\n\";");
        _source.println("    throw new Error(msg);");
        _source.println("};");
        _source.println();

        // Abstract method to obtain the a state's supported
        // transitions.
        if (_reflectFlag == true)
        {
            _source.print(context);
            _source.println("State.prototype.getTransitions = function () {");
            _source.println("    return this.transitions;");
            _source.println("};");
            _source.println();
        }

        // Have each map print out its source code now.
        for (SmcMap map: maps)
        {
            map.accept(this);
        }

        _source.println();

        // The state name "map::state" must be changed to
        // "map.state".
        if ((index = startState.indexOf("::")) >= 0)
        {
            javaState =
                startState.substring(0, index) +
                "." +
                startState.substring(index + 2);
        }
        else
        {
            javaState = startState;
        }

        // Generate the context class' constructor.
        _source.print("function ");
        _source.print(fsmClassName);
        _source.println(" (owner) {");
        _source.print("    FSMContext.call(this, ");
        _source.print(javaState);
        _source.println(");");
        _source.println("    this.owner = owner;");
        _source.println('}');
        // Inheritance.
        _source.print(fsmClassName);
        _source.println(".prototype = new FSMContext();");
        // Register in global.
        _source.println("try {");
        _source.print("    global.");
        _source.print(fsmClassName);
        _source.print(" = ");
        _source.print(fsmClassName);
        _source.println(';');
        _source.println("} catch (ex) {}");
        _source.println();

        // Generate the start abstract method which requires
        // executes the initial state's entry actions.
        _source.print(fsmClassName);
        _source.println(".prototype.enterStartState = function () {");
        _source.println("    this.getState().Entry(this);");
        _source.println("};");
        _source.println();

        // Generate the default transition methods.
        for (SmcTransition trans: transitions)
        {
            if (trans.getName().equals("Default") == false)
            {
                _source.print(fsmClassName);
                _source.print(".prototype.");
                _source.print(trans.getName());
                _source.print(" = function (");

                params = trans.getParameters();
                for (pit = params.iterator(), separator = "";
                     pit.hasNext() == true;
                     separator = ", ")
                {
                    _source.print(separator);
                    (pit.next()).accept(this);
                }
                _source.println(") {");

                // Save away the transition name in case it is
                // need in an UndefinedTransitionException.
                _source.print("    this.transition = '");
                _source.print(trans.getName());
                _source.println("';");

                _source.print("    this.getState().");
                _source.print(trans.getName());
                _source.print("(this");

                for (pit = params.iterator();
                     pit.hasNext() == true;
                    )
                {
                    _source.print(", ");
                    _source.print((pit.next()).getName());
                }
                _source.println(");");
                _source.println("    this.transition = '';");

                _source.println("};");
                _source.println();
            }
        }

        if (_reflectFlag == true)
        {
            String mapName;

            // create the state array.
            _source.print(fsmClassName);
            _source.println(".prototype.states = [");

            separator = "";
            for (SmcMap map: maps)
            {
                mapName = map.getName();

                for (SmcState state: map.getStates())
                {
                    _source.print(separator);
                    _source.print("    ");
                    _source.print(mapName);
                    _source.print(".");
                    _source.print(state.getClassName());

                    separator = ",\n";
                }
            }

            _source.println();
            _source.println("];");

            // getStates() method.
            _source.print(fsmClassName);
            _source.println(".prototype.getStates = function () {");
            _source.println("    return this.prototype.states;");
            _source.println("};");
            _source.println();

            // create the transition array.
            _source.print(fsmClassName);
            _source.println(".prototype.transitions = [");

            separator = "";
            for (SmcTransition trans: transitions)
            {
                _source.print(separator);
                _source.print("    '");
                _source.print(trans.getName());
                _source.print("'");

                separator = ",\n";
            }

            _source.println();
            _source.println("];");

            // getTransitions() method.
            _source.print(fsmClassName);
            _source.println(".prototype.getTransitions = function () {");
            _source.println("    return this.prototype.transitions;");
            _source.println("};");
        }

        _source.println();
        _source.println("/*");
        _source.println(" * Local variables:");
        _source.println(" *  buffer-read-only: t");
        _source.println(" * End:");
        _source.println(" */");

        return;
    } // end of visit(SmcFSM)

    /**
     * Emits JavaScript code for the FSM map.
     * @param map emit JavaScript code for this map.
     */
    public void visit(SmcMap map)
    {
        List<SmcTransition> definedDefaultTransitions;
        SmcState defaultState = map.getDefaultState();
        String context = map.getFSM().getContext();
        String mapName = map.getName();
        List<SmcState> states = map.getStates();

        // Initialize the default transition list to all the
        // default state's transitions.
        if (defaultState != null)
        {
            definedDefaultTransitions =
                defaultState.getTransitions();
        }
        else
        {
            definedDefaultTransitions =
                new ArrayList<SmcTransition>();
        }

        // Declare the constructor.
        _source.println();
        _source.print("function ");
        _source.print(mapName);
        _source.print("_DefaultState");
        _source.println(" (name, id) {");
        _source.println("    State.call(this, name, id);");
        _source.println("}");
        // Inheritance.
        _source.print(mapName);
        _source.print("_DefaultState.prototype = new ");
        _source.print(context);
        _source.println("State();");
        _source.println();

        _source.print("var ");
        _source.print(mapName);
        _source.println(" = {};");
         // Store an instance.
        _source.print(mapName);
        _source.print(".DefaultState = new ");
        _source.print(mapName);
        _source.print("_DefaultState");
        _source.print("('");
        _source.print(mapName);
        _source.print("::DefaultState', ");
        _source.print(SmcMap.getNextStateId());
        _source.println(");");


        // Declare the user-defined default transitions first.
        _indent = "";
        for (SmcTransition trans: definedDefaultTransitions)
        {
            trans.accept(this);
        }

        // If -reflect was specified, then generate the
        // _transitions map.
        if (_reflectFlag == true)
        {
            List<SmcTransition> allTransitions =
                map.getFSM().getTransitions();
            String transName;
            String transDefinition;
            String separator = "";

            // Now output the transition collection's
            // initialization.
            _source.println();
            _source.print(mapName);
            _source.println(".DefaultState.transitions = {");

            // Now place all transition names and states into the
            // map.
            for (SmcTransition transition: allTransitions)
            {
                transName = transition.getName();

                // If the transition is defined in this map's
                // default state, then the value is 2.
                if (definedDefaultTransitions.contains(
                        transition) == true)
                {
                    transDefinition = "2";
                }
                // Otherwise the value is 0 - undefined.
                else
                {
                    transDefinition = "0";
                }

                _source.print(separator);
                _source.print("    '");
                _source.print(transName);
                _source.print("': ");
                _source.print(transDefinition);

                separator = ",\n";
            }
            _source.println();
            _source.println("};");
        }

        for (SmcState state: states)
        {
            state.accept(this);
        }

        return;
    } // end of visit(SmcMap)

    /**
     * Emits JavaScript code for this FSM state.
     * @param state emits JavaScript code for this state.
     */
    public void visit(SmcState state)
    {
        SmcMap map = state.getMap();
        String context = map.getFSM().getContext();
        String fsmClassName = map.getFSM().getFsmClassName();
        String mapName = map.getName();
        String stateName = state.getClassName();
        List<SmcAction> actions;

        // Declare the constructor.
        _source.println();
        _source.print("function ");
        _source.print(mapName);
        _source.print('_');
        _source.print(stateName);
        _source.println(" (name, id) {");
        _source.println("    State.call(this, name, id);");
        _source.println("}");
        // Inheritance.
        _source.print(mapName);
        _source.print('_');
        _source.print(stateName);
        _source.print(".prototype = ");
        _source.print(mapName);
        _source.println(".DefaultState;");
        _source.println();

        // Store an instance.
        _source.print(mapName);
        _source.print('.');
        _source.print(stateName);
        _source.print(" = new ");
        _source.print(mapName);
        _source.print('_');
        _source.print(stateName);
        _source.print("('");
        _source.print(mapName);
        _source.print("::");
        _source.print(stateName);
        _source.print("', ");
        _source.print(SmcMap.getNextStateId());
        _source.println(");");

        // Add the entry() and exit() member functions if this
        // state defines them.
        actions = state.getEntryActions();
        if (actions != null && actions.size() > 0)
        {
            _source.println();
            _source.print(mapName);
            _source.print('.');
            _source.print(stateName);
            _source.println(".Entry = function (fsm) {");
            _source.println("    var ctxt = fsm.owner;");

            // Generate the actions associated with this code.
            _indent = "    ";
            for (SmcAction action: actions)
            {
                action.accept(this);
            }

            _source.println("};");
        }

        actions = state.getExitActions();
        if (actions != null && actions.size() > 0)
        {
            _source.println();
            _source.print(mapName);
            _source.print('.');
            _source.print(stateName);
            _source.println(".Exit = function (fsm) {");
            _source.println("    var ctxt = fsm.owner;");

            // Generate the actions associated with this code.
            _indent = "    ";
            for (SmcAction action: actions)
            {
                action.accept(this);
            }

            _source.println("};");
        }

        // Have each transition generate its code.
        _indent = "";
        for (SmcTransition transition: state.getTransitions())
        {
            transition.accept(this);
        }

        // If -reflect was specified, then generate the
        // _transitions map.
        if (_reflectFlag == true)
        {
            List<SmcTransition> allTransitions =
                map.getFSM().getTransitions();
            List<SmcTransition> stateTransitions =
                state.getTransitions();
            SmcState defaultState = map.getDefaultState();
            List<SmcTransition> defaultTransitions;
            String transName;
            String transDefinition;
            String separator = "";

            // Initialize the default transition list to all the
            // default state's transitions.
            if (defaultState != null)
            {
                defaultTransitions =
                    defaultState.getTransitions();
            }
            else
            {
                defaultTransitions =
                    new ArrayList<SmcTransition>();
            }

            // Now output the transition collection's
            // initialization.
            _source.println();
            _source.print(mapName);
            _source.print('.');
            _source.print(stateName);
            _source.println(".transitions = {");

            // Now place all transition names and states into the
            // map.
            for (SmcTransition transition: allTransitions)
            {
                transName = transition.getName();

                // If the transition is in this state, then its
                // value is 1.
                if (stateTransitions.contains(
                        transition) == true)
                {
                    transDefinition = "1";
                }
                // If the transition is defined in this map's
                // default state, then the value is 2.
                else if (defaultTransitions.contains(
                             transition) == true)
                {
                    transDefinition = "2";
                }
                // Otherwise the value is 0 - undefined.
                else
                {
                    transDefinition = "0";
                }

                _source.print(separator);
                _source.print("    '");
                _source.print(transName);
                _source.print("': ");
                _source.print(transDefinition);

                separator = ",\n";
            }
            _source.println();

            _source.println("};");
        }

        return;
    } // end of visit(SmcState)

    /**
     * Emits JavaScript code for this FSM state transition.
     * @param transition emits JavaScript code for this state transition.
     */
    public void visit(SmcTransition transition)
    {
        SmcState state = transition.getState();
        SmcMap map = state.getMap();
        String context = map.getFSM().getContext();
        String fsmClassName = map.getFSM().getFsmClassName();
        String mapName = map.getName();
        String stateName = state.getClassName();
        String instanceName = state.getInstanceName();
        String transName = transition.getName();
        List<SmcParameter> parameters =
            transition.getParameters();
        List<SmcGuard> guards = transition.getGuards();
        boolean nullCondition = false;
        Iterator<SmcParameter> pit;
        Iterator<SmcGuard> git;
        SmcGuard guard;

        _source.println();
        _source.print(mapName);
        _source.print('.');
        _source.print(instanceName);
        _source.print('.');
        _source.print(transName);
        _source.print(" = function (fsm");

        // Add user-defined parameters.
        for (SmcParameter parameter: parameters)
        {
            _source.print(", ");
            parameter.accept(this);
        }
        _source.println(") {");

        // All transitions have a "ctxt" local variable.
        // 8/14/2003:
        // Do this only if there are any transition actions or
        // guard conditions which reference it.
        if (transition.hasCtxtReference() == true)
        {
            _source.println("    var ctxt = fsm.owner;");
        }

        // Output state exit.
        if (_debugLevel >= DEBUG_LEVEL_0)
        {
            _source.println("    if (fsm.debugFlag) {");
            _source.print("        fsm.debugStream.write(\"LEAVING STATE   : ");
            _source.print(mapName);
            _source.print('.');
            _source.print(stateName);
            _source.println("\\n\");");
            _source.println("    }");
        }

        // Loop through the guards and print each one.
        for (git = guards.iterator(),
                 _guardIndex = 0,
                 _guardCount = guards.size();
             git.hasNext() == true;
             ++_guardIndex)
        {
            guard = git.next();

            // Count up the guards with no condition.
            if (guard.getCondition().length() == 0)
            {
                nullCondition = true;
            }

            guard.accept(this);
        }

        // If all guards have a condition, then create a final
        // "else" clause which passes control to the default
        // transition. Pass all arguments into the default
        // transition.
        if (_guardIndex > 0 && nullCondition == false)
        {
            if (_guardCount == 1)
            {
                _source.println("    }");
            }

            _source.println("    else {");

            // Call the super class' transition method
            _source.print(_indent);
            _source.print("        ");
            _source.print(mapName);
            _source.print(".DefaultState.");
            if (instanceName.equals("DefaultState") == false)
            {
                _source.print(transName);
                _source.print("(fsm");

                // Add user-defined parameters.
                for (SmcParameter param: parameters)
                {
                    _source.print(", ");
                    _source.print(param.getName());
                }
            }
            else
            {
                _source.print("Default(fsm");
            }
            _source.println(");");
            _source.println("    }");
        }
        // Need to add a final newline after a multiguard block.
        else if (_guardCount > 1)
        {
            _source.println();
        }

        _source.println("};");

        return;
    } // end of visit(SmcTransition)

    /**
     * Emits JavaScript code for this FSM transition guard.
     * @param guard emits JavaScript code for this transition guard.
     */
    public void visit(SmcGuard guard)
    {
        SmcTransition transition = guard.getTransition();
        SmcState state = transition.getState();
        SmcMap map = state.getMap();
        String context = map.getFSM().getContext();
        String mapName = map.getName();
        String stateName = state.getClassName();
        String transName = transition.getName();
        TransType transType = guard.getTransType();
        boolean loopbackFlag = false;
        String indent2;
        String indent3;
        String indent4;
        String endStateName = guard.getEndState();
        String fqEndStateName = "";
        String pushStateName = guard.getPushState();
        String condition = guard.getCondition();
        List<SmcAction> actions = guard.getActions();
        boolean hasActions = !(actions.isEmpty());

        // If this guard's end state is not of the form
        // "map::state", then prepend the map name to the
        // state name.
        // DON'T DO THIS IF THIS IS A POP TRANSITION!
        // The "state" is actually a transition name.
        if (transType != TransType.TRANS_POP &&
            endStateName.length () > 0 &&
            endStateName.equals(SmcElement.NIL_STATE) == false)
        {
            endStateName = scopeStateName(endStateName, mapName);
        }

        // Qualify the state and push state names as well.
        stateName = scopeStateName(stateName, mapName);
        pushStateName = scopeStateName(pushStateName, mapName);

        loopbackFlag = isLoopback(transType, endStateName);

        // The guard code generation is a bit tricky. The first
        // question is how many guards are there? If there are
        // more than one, then we will need to generate the
        // proper "if-then-else" code.
        if (_guardCount > 1)
        {
            indent2 = _indent + "        ";

            // There are multiple guards.
            // Is this the first guard?
            if (_guardIndex == 0 && condition.length() > 0)
            {
                // Yes, this is the first. This means an "if"
                // should be used.
                _source.print(_indent);
                _source.print("    if (");
                _source.print(condition);
                _source.println(") {");
            }
            else if (condition.length() > 0)
            {
                // No, this is not the first transition but it
                // does have a condition. Use an "else if".
                _source.println();
                _source.print(_indent);
                _source.print("    else if (");
                _source.print(condition);
                _source.println(") {");
            }
            else
            {
                // This is not the first transition and it has
                // no condition.
                _source.println();
                _source.print(_indent);
                _source.println("    else {");
            }
        }
        // There is only one guard. Does this guard have a
        // condition?
        else if (condition.length() == 0)
        {
            // No. This is a plain, old. vanilla transition.
            indent2 = _indent + "    ";
        }
        else
        {
            // Yes there is a condition.
            indent2 = _indent + "        ";

            _source.print(_indent);
            _source.print("    if (");
            _source.print(condition);
            _source.println(") {");
        }

        // Now that the necessary conditions are in place, it's
        // time to dump out the transition's actions. First, do
        // the proper handling of the state change. If this
        // transition has no actions, then set the end state
        // immediately. Otherwise, unset the current state so
        // that if an action tries to issue a transition, it will
        // fail.
        if (hasActions == false || loopbackFlag == false)
        {
            fqEndStateName = endStateName;
        }
        // Save away the current state if this is a loopback
        // transition. Storing current state allows the
        // current state to be cleared before any actions are
        // executed. Remember: actions are not allowed to
        // issue transitions and clearing the current state
        // prevents them from doing do.
        else
        {
            fqEndStateName = "endState";

            _source.print(indent2);
            _source.print("var ");
            _source.print(fqEndStateName);
            _source.println(" = fsm.getState();");
        }

        // _source.println();

        // Dump out the exit actions - but only for the first
        // guard.
        // v. 1.0, beta 3: Not any more. The exit actions are
        // executed only if 1) this is a standard, non-loopback
        // transition or a pop transition.
        if (transType == TransType.TRANS_POP ||
            loopbackFlag == false)
        {
            if (_debugLevel >= DEBUG_LEVEL_1)
            {
                _source.print(indent2);
                _source.println("if (fsm.debugFlag) {");
                _source.print(indent2);
                _source.print("    fsm.debugStream.write(\"BEFORE EXIT     : ");
                _source.print(stateName);
                _source.println(".exit()\\n\");");
                _source.print(indent2);
                _source.println("}");
            }

            _source.print(indent2);
            _source.println("fsm.getState().Exit(fsm);");

            if (_debugLevel >= DEBUG_LEVEL_1)
            {
                _source.print(indent2);
                _source.println("if (fsm.debugFlag) {");
                _source.print(indent2);
                _source.print("    fsm.debugStream.write(\"AFTER EXIT      : ");
                _source.print(stateName);
                _source.println(".exit()\\n\");");
                _source.print(indent2);
                _source.println("    }");
            }

        }

        // Output transition to debug stream.
        if (_debugLevel >= DEBUG_LEVEL_0)
        {
            List<SmcParameter> parameters =
                transition.getParameters();
            Iterator<SmcParameter> pit;
            String sep;

            indent4 = _indent;
            if (_noCatchFlag == false)
            {
                _indent = indent2;
            }

            _source.print(_indent);
            _source.println("if (fsm.debugFlag) {");
            _source.print(_indent);
            _source.print("    fsm.debugStream.write(\"ENTER TRANSITION: ");
            _source.print(stateName);
            _source.print('.');
            _source.print(transName);

            _source.print('(');
            for (pit = parameters.iterator(), sep = "";
                 pit.hasNext() == true;
                 sep = ", ")
            {
                _source.print(sep);
                (pit.next()).accept(this);
            }
            _source.print(')');

            _source.println("\\n\");");
            _source.print(_indent);
            _source.println("}");

            _indent = indent4;
        }

        // Dump out this transition's actions.
        if (hasActions == false)
        {
            if (condition.length() > 0)
            {
                _source.print(indent2);
                _source.println("// No actions.");
            }

            indent3 = indent2;
        }
        else
        {
            // Now that we are in the transition, clear the
            // current state.
            _source.print(indent2);
            _source.println("fsm.clearState();");

            // v. 2.0.0: Place the actions inside a try/finally
            // block. This way the state will be set before an
            // exception leaves the transition method.
            // v. 2.2.0: Check if the user has turned off this
            // feature first.
            if (_noCatchFlag == false)
            {
                _source.print(indent2);
                _source.println("try {");

                indent3 = indent2 + "    ";
            }
            else
            {
                indent3 = indent2;
            }

            indent4 = _indent;
            _indent = indent3;

            for (SmcAction action: actions)
            {
                action.accept(this);
            }

            _indent = indent4;

            // v. 2.2.0: Check if the user has turned off this
            // feature first.
            if (_noCatchFlag == false)
            {
                _source.print(indent2);
                _source.println('}');
                _source.print(indent2);
                _source.println("finally {");
            }
        }

        // Output transition to debug stream.
        if (_debugLevel >= DEBUG_LEVEL_0)
        {
            List<SmcParameter> parameters =
                transition.getParameters();
            Iterator<SmcParameter> pit;
            String sep;

            indent4 = _indent;
            _indent = indent3;

            _source.print(_indent);
            _source.println("if (fsm.debugFlag) {");
            _source.print(_indent);
            _source.print("    fsm.debugStream.write(\"EXIT TRANSITION : ");
            _source.print(stateName);
            _source.print('.');
            _source.print(transName);

            _source.print('(');
            for (pit = parameters.iterator(), sep = "";
                 pit.hasNext() == true;
                 sep = ", ")
            {
                _source.print(sep);
                (pit.next()).accept(this);
            }
            _source.print(')');

            _source.println("\\n\");");
            _source.print(_indent);
            _source.println("}");

            _indent = indent4;
        }

        // Print the setState() call, if necessary. Do NOT
        // generate the set state it:
        // 1. The transition has no actions AND is a loopback OR
        // 2. This is a push or pop transition.
        if (transType == TransType.TRANS_SET &&
            (hasActions == true || loopbackFlag == false))
        {
            _source.print(indent3);
            _source.print("fsm.setState(");
            _source.print(fqEndStateName);
            _source.println(");");
        }
        else if (transType == TransType.TRANS_PUSH)
        {
            // Set the next state so this it can be pushed
            // onto the state stack. But only do so if a clear
            // state was done.
            if (loopbackFlag == false || hasActions == true)
            {
                _source.print(indent3);
                _source.print("fsm.setState(");
                _source.print(fqEndStateName);
                _source.println(");");
            }

            // Before doing the push, execute the end state's
            // entry actions (if any) if this is not a loopback.
            if (loopbackFlag == false)
            {
                _source.print(indent3);
                _source.println("fsm.getState().Entry(fsm);");
            }

            _source.print(indent3);
            _source.print("fsm.pushState(");
            _source.print(pushStateName);
            _source.println(");");
        }
        else if (transType == TransType.TRANS_POP)
        {
            _source.print(indent3);
            _source.println("fsm.popState();");
        }

        // Perform the new state's enty actions.
        // v. 1.0, beta 3: Not any more. The entry actions are
        // executed only if 1) this is a standard, non-loopback
        // transition or a push transition.
        if ((transType == TransType.TRANS_SET &&
             loopbackFlag == false) ||
             transType == TransType.TRANS_PUSH)
        {
            if (_debugLevel >= DEBUG_LEVEL_1)
            {
                _source.print(indent3);
                _source.println("if (fsm.debugFlag) {");
                _source.print(indent3);
                _source.print("    fsm.debugStream.write(\"BEFORE ENTRY    : ");
                _source.print(fqEndStateName);
                _source.println(".Entry()\\n\");");
                _source.print(indent3);
                _source.println("}");
            }

            _source.print(indent3);
            _source.println("fsm.getState().Entry(fsm);");

            if (_debugLevel >= DEBUG_LEVEL_1)
            {
                _source.print(indent3);
                _source.println("if (fsm.debugFlag) {");
                _source.print(indent3);
                _source.print("    fsm.debugStream.write(\"AFTER ENTRY     : ");
                _source.print(fqEndStateName);
                _source.println(".Entry()\\n\");");
                _source.print(indent3);
                _source.println("}");
            }
        }

        // If there was a try/finally, then put the closing
        // brace on the finally block.
        // v. 2.2.0: Check if the user has turned off this
        // feature first.
        if (hasActions == true && _noCatchFlag == false)
        {
            _source.print(indent2);
            _source.println('}');
        }

        // If there is a transition associated with the pop, then
        // issue that transition here.
        if (transType == TransType.TRANS_POP &&
            endStateName.equals(SmcElement.NIL_STATE) == false &&
            endStateName.length() > 0)
        {
            String popArgs = guard.getPopArgs();

            _source.println();
            _source.print(indent2);
            _source.print("fsm.");
            _source.print(endStateName);
            _source.print("(");

            // Output any and all pop arguments.
            if (popArgs.length() > 0)
            {
                _source.print(popArgs);
            }
            _source.println(");");
        }

        // If this is a guarded transition, it will be necessary
        // to close off the "if" body. DON'T PRINT A NEW LINE!
        // Why? Because an "else" or "else if" may follow and we
        // won't know until we go back to the transition source
        // generator whether all clauses have been done.
        if (_guardCount > 1)
        {
            _source.print(_indent);
            _source.print("    }");
        }

        return;
    } // end of visit(SmcGuard)

    /**
     * Emits JavaScript code for this FSM action.
     * @param action emits JavaScript code for this action.
     */
    public void visit(SmcAction action)
    {
        String name = action.getName();
        List<String> arguments = action.getArguments();

        if (action.isProperty() == true)
        {
            _source.print(_indent);
            _source.print("ctxt.");
            _source.print(name);
            _source.print(" = ");
            _source.print(arguments.get(0));
            _source.println(';');
        }
        else
        {
            // Need to distinguish between FSMContext actions and
            // application class actions. If the action is
            // "emptyStateStack", then pass it to the context.
            // Otherwise, let the application class handle it.
            _source.print(_indent);
            if (action.isEmptyStateStack() == true)
            {
                _source.println("fsm.emptyStateStack();");
            }
            else
            {
                Iterator<String> it;
                String sep;

                _source.print("ctxt.");
                _source.print(name);
                _source.print("(");

                for (it = arguments.iterator(), sep = "";
                     it.hasNext() == true;
                     sep = ", ")
                {
                    _source.print(sep);
                    _source.print(it.next());
                }

                _source.println(");");
            }
        }

        return;
    } // end of visit(SmcAction)

    /**
     * Emits JavaScript code for this transition parameter.
     * @param parameter emits JavaScript code for this transition
     * parameter.
     */
    public void visit(SmcParameter parameter)
    {
        _source.print(parameter.getName());

        return;
    } // end of visit(SmcParameter)

    //
    // end of SmcVisitor Abstract Method Impelementation.
    //-----------------------------------------------------------

//---------------------------------------------------------------
// Member data
//
} // end of class SmcJSGenerator


//
// CHANGE LOG
// $Log$
// Revision 1.5  2013/12/15 16:32:06  fperrad
// full refactor of JavaScript
//
// Revision 1.4  2013/07/14 14:32:38  cwrapp
// check in for release 6.2.0
//
// Revision 1.3  2011/02/16 18:02:01  nitin-nizhawan
// added prototype channing to allow instanceof operator to work
//
// Revision 1.2  2011/02/14 21:29:56  nitin-nizhawan
// corrected some build errors
//
// Revision 1.1  2011/02/14 18:32:04  nitin-nizhawan
// added generator class for JavaScript
//
//
